workflows:
  ios-app:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      vars:
        XCODE_SCHEME: "GlazeKnowledgeBase"
        XCODE_PROJECT: "GlazeKnowledgeBase.swiftpm"
    scripts:
      - name: Build for Simulator
        script: |
          cd $XCODE_PROJECT
          xcodebuild build \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=latest' \
            -derivedDataPath ../build \
            CODE_SIGNING_ALLOWED=NO
      - name: Package Simulator App
        script: |
          cd build/Build/Products/Debug-iphonesimulator
          zip -r ../../../../GlazeKnowledgeBase-simulator.zip GlazeKnowledgeBase.app
    artifacts:
      - GlazeKnowledgeBase-simulator.zip
      - build/Build/Products/**/*.app
