workflows:
  ios-app:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build iOS App
        script: |
          cd GlazeKnowledgeBase.swiftpm
          xcodebuild build \
            -scheme GlazeKnowledgeBase \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -allowProvisioningUpdates
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
